name: "openscpca-cell-type-neuroblastoma-04"
channels:
  - conda-forge
  - bioconda
platforms:
  - linux-64
  - osx-64
  - osx-arm64
dependencies:
  - python=3.11
  - awscli>=2.15
  - conda-lock>=2.5
  - jq>=1.7
  - pre-commit>=3.6
  - session-info>=1.0
  - anndata
  - pytorch::pytorch-cuda=12.4
  - pip
  - pip:
    - scvi-tools
    - numpy==1.26.4
    - matplotlib
    - "jax[cuda12]"
