name: "openscpca-cell-type-neuroblastoma-04-gpu"
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
platforms:
  - linux-64
dependencies:
  - python=3.11
  - conda-lock=2.5
  - jq=1.7
  - pre-commit>=3.6
  - awscli>=2.15
  - anndata
  - pytorch::pytorch-cuda
  - scvi-tools
  - pip
  - pip:
    - "jax[cuda12]"

