name: "gpu-cellassign"
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
platforms:
  - linux-64
dependencies:
  - python=3.11
  - awscli=2.15
  - conda-lock=2.5
  - jq=1.7
  - pre-commit=3.6
  - session-info=1.0
  - anndata
  - pytorch::pytorch-cuda
  - pip
  - pip:
    - scvi-tools
    - "jax[cuda12]"

