name: "libcublas"
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
platforms:
  - linux-64
  - osx-64
dependencies:
  - python=3.11
  - conda-lock=2.5
  - jq=1.7
  - anndata
  - conda-forge::libcublas
  - pip
  - pip:
    - scvi-tools
    - "jax[cuda12]"
